# Cloudflare Tunnel Configuration Example
# Copy this file to config.yml and update with your tunnel details

tunnel: your-tunnel-id-here
credentials-file: /etc/cloudflared/your-tunnel-id-here.json

ingress:
  - hostname: search.loonylabs.dev  # Your domain for SearXNG
    service: http://proxy:3000      # Target the proxy service (with API key auth)
  - service: http_status:404
